### ISSUE TITLE
Error due to deprecated function input "skip_footer"

### ISSUE THREAD

**Issue by avanderburg** [timothydmorton/VESPA#14]
In trilegal.py, need to change the line:
df = pd.read_table(outfile, sep='\s+', skip_footer=1, engine='python')
to
df = pd.read_table(outfile, sep='\s+', skipfooter=1, engine='python')

(lose the underscore in skip_footer)

**Comment by timothydmorton** [comment]
Yup--This is already changed on master with 2ad59c6.
