### ISSUE TITLE
New VESPA incompatible with new isochrones version

### ISSUE THREAD

**Issue by nespinoza** [timothydmorton/VESPA#4]
Hi Tim,

 I was writing to let you know that due to the recent upgrade on the isochrones package, VESPA is not working properly due to various reasons. The main one is that the BinaryStarModel and TripleStarModel no longer work as expected by VESPA (because now, these have to be called directly with StarModel and setting N=2 and 3, respectively), but after doing some modifications to that, other parts of the code fail as well. I've been working on this, but don't want to push further if you are already working on this; I suppose you are planning an upgrade on VESPA in order for it to be compatible with the new isochrones version, right?

Best

**Comment by timothydmorton** [comment]
That is correct! The current vespa is not compatible beyond isochrones
0.9.1. I've upgraded isochrones but not yet vespa... Stay tuned!

**Comment by timothydmorton** [comment]
I've now changed the `install-requires` in the setup.py to require isochrones v0.9.1.
