### ISSUE TITLE
VESPA seems imcompatible with the newest isochrones

### ISSUE THREAD

**Issue by Li-Yangyang** [timothydmorton/VESPA#9]
Hi, 
I've updated the isochrones with the solved problem #43 of isochrones but it seems there are something wrong with VESPA's calcfpp which said:
Traceback (most recent call last):
  ```
File "./anaconda2/bin/calcfpp", line 68, in <module>
    from isochrones import StarModel, BinaryStarModel, TripleStarModel
ImportError: cannot import name BinaryStarModel

```
Do you know how to fix it?
Thanks

**Comment by iancrossfield** [comment]
I ran into this same problem. No luck yet on a workaround.

**Comment by timothydmorton** [comment]
Are y'all sure you're running isochrones 0.9.1 and not 1.0?  1.0 is not compatible with vespa yet.

**Comment by timothydmorton** [comment]
I've recently successfully run all the Kepler DR25 KOIs after a few code modifications to deal with the dr25 data.  The conda environment is [this](https://github.com/timothydmorton/koi-fpp/blob/dr25/environment.yml), along with the current `dr25` branches of both `isochrones` and `vespa`.

**Comment by timothydmorton** [comment]
(sorry this is all still kind of a mess.  I haven't had any effort available recently to move toward cleaning up all this stuff, so I apologize for the sloppiness.)

**Comment by iancrossfield** [comment]
@Li-Yangyang  -- uninstalling isochrones, then doing 'pip install isochrones==0.9.1' got things running for me. You might need to reinstall vespa too...
@timothydmorton -- no apologies necessary, most of us can only aspire to be as neat as your 'sloppiness'

**Comment by elisabethadams** [comment]
This doesn't seem to work for me -- I've tried switching isochrones versions around, and while I can get isochrones 1.1 to work fine (defined as: I can successfully run starfit in a folder with a star.ini file) I can't get v0.9.1 to work anymore. 

Specifically, when I do try to use starfit with 0.9.1, I get  

> You have a wrong/corrupted/outdated Dartmouth triangulation! Delete /Users/era/.isochrones/dartmouth.tri and try re-importing to download afresh.

And then if I do delete that file and try again, I get the famous ischrones issue #43 (AttributeError: 'Delaunay' object has no attribute '_points') 

But the fix to that issue (using write_tri to write my own file locally) doesn't work because those functions aren't in 0.9.1. 

(Nor does writing the file in v1.1 and trying to use it in 0.9.1 -- I suspected as much but had to test it, on the off chance it would help.) 

I am a little stuck on how to get a functional vespa installation!

**Comment by timothydmorton** [comment]
Yes, I'm sorry about all this.  As you may know, I have barely been able to
touch vespa/isochrones at all recently.  I may get around to checking all
this out soon and straightening everything out.

In the meantime, give this a shot:  try using the 'dr25-1.0' branches of
both isochrones and vespa.  I believe that is the code I used to run the
Kepler DR25 FPPs, and they should be compatible.  Do let me know if that
works.

**Comment by elisabethadams** [comment]
[Let me know which funding agency wants letters of support or something to give you time to work on this ;) ]

Anyhow, that branch sort of works, in that I finally got things installed, but: 

(1) For whatever reason, calc_fpp won't actually run the models for the single/binary/triple star automatically (like it used to). However, if you run them independently with e.g.

> starfit --models dartmouth --binary

then calcfpp will proceed. (This is scriptable and if that were the only problem I wouldn't care anymore.)

(2) But then it fails to download a file (I left it overnight, then tried again -- no dice).

> Getting TRILEGAL simulation at 125.00716, 14.019461...
TRILEGAL is being called with 
 l=209.822407 deg, b=25.848304 deg, area=1.000000 sqrdeg
 Av=0.094 with 0.10 fractional r.m.s. spread 
 in the kepler_2mass system, complete down to mag=27.0 in its 1th filter, use_binaries set to 0.
retrieving data from output949770385938.dat ...
still running...
still running...
still running... [etc. forever]

The log file (lixo) says:

> --2018-03-02 16:10:32--  http://stev.oapd.inaf.it/~lgirardi/tmp/output949770385938.dat
Resolving stev.oapd.inaf.it (stev.oapd.inaf.it)... 193.206.241.134
Connecting to stev.oapd.inaf.it (stev.oapd.inaf.it)|193.206.241.134|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-02 16:10:33 ERROR 404: Not Found.

So, I dunno, maybe the Italian server is having a bad day and I should check back later. It might just be time to call it a week.

Thanks again, Tim.

**Comment by timothydmorton** [comment]
Thanks for being a willing and patient guinea pig Elisabeth!  Your tests are helpful.  I just pushed a fix to the `dr25-1.0` branch that just merges in a PR from @iancrossfield that had corrected something about TRILEGAL access.  That had been in place on master and on my local copy of the branch, but I hadn't yet pushed it.  So that problem should be fixed at least; let me know!

**Comment by timothydmorton** [comment]
[And to answer your first question, you can thank NASA XRP for a poor review of my "Development and support of planet validation software for the TESS era" proposal.  Or more accurately, perhaps, just out-of-touch and/or tone-deaf community reviewers.  Unfortunately the way things work, there's no real centralized responsibility for any of these things....]

**Comment by elisabethadams** [comment]
Two steps forward, one step back, eventually it will work.

The new branch makes it most of the way through calcfpp, but then fails, I think at the TRILEGAL step, though the actual error is opaque. Any chance you've got a quick fix on hand for this too?

> 2018-03-05 16:40:29,311: Fitting trapezoid models for EBs (Double Period)...
> 2018-03-05 16:40:32,005: Done.
> 2018-03-05 16:40:32,205: Getting TRILEGAL simulation at 125.00716, 14.019461...
> 2018-03-05 16:41:58,457: Error generating BEB population.
> 2018-03-05 16:41:58,458: FPP calculation failed for ..
> Traceback (most recent call last):
>   File "/anaconda/lib/python2.7/site-packages/VESPA-0.4.10-py2.7-macosx-10.6-x86_64.egg/EGG-INFO/scripts/calcfpp", line 137, in <module>
>     n=args.n)
>   File "//anaconda/lib/python2.7/site-packages/VESPA-0.4.10-py2.7-macosx-10.6-x86_64.egg/vespa/fpp.py", line 348, in from_ini
>     savefile=popset_file, **kwargs)
>   File "//anaconda/lib/python2.7/site-packages/VESPA-0.4.10-py2.7-macosx-10.6-x86_64.egg/vespa/populations.py", line 2015, in __init__
>     do_only=do_only)
>   File "//anaconda/lib/python2.7/site-packages/VESPA-0.4.10-py2.7-macosx-10.6-x86_64.egg/vespa/populations.py", line 2130, in generate
>     mags=mags, MAfn=MAfn, n=n, **beb_kws)
>   File "//anaconda/lib/python2.7/site-packages/VESPA-0.4.10-py2.7-macosx-10.6-x86_64.egg/vespa/populations.py", line 1735, in __init__
>     maxrad=maxrad, f_binary=f_binary, **kwargs)
>   File "//anaconda/lib/python2.7/site-packages/VESPA-0.4.10-py2.7-macosx-10.6-x86_64.egg/vespa/populations.py", line 1764, in generate
>     maxrad=maxrad, **kwargs)
>   File "//anaconda/lib/python2.7/site-packages/VESPA-0.4.10-py2.7-macosx-10.6-x86_64.egg/vespa/stars/populations.py", line 2509, in __init__
>     get_trilegal(basefilename,ra,dec,**kwargs)
>   File "//anaconda/lib/python2.7/site-packages/VESPA-0.4.10-py2.7-macosx-10.6-x86_64.egg/vespa/stars/trilegal.py", line 97, in get_trilegal
>     df = pd.read_table(outfile, sep='\s+', skip_footer=1, engine='python')
>   File "//anaconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 595, in parser_f
>     FutureWarning, stacklevel=2)
> FutureWarning: The 'skip_footer' argument has been deprecated and will be removed in a future version. Please use the 'skipfooter' argument instead.
>

**Comment by timothydmorton** [comment]
Not sure why a `FutureWarning` is raising an exception here, but it seems like it should be a pretty trivial change to replace `skip_footer` with `skipfooter`.  Feel free to give that a shot to see if it works for you, and then submit a PR (or just let me know if it works, and I can fix it when I get the chance).

**Comment by elisabethadams** [comment]
Yay, that did the trick -- I have an FPP. Thanks... until next time ;)

**Comment by timothydmorton** [comment]
Glad to hear it; I just made this change on master (https://github.com/timothydmorton/VESPA/commit/2ad59c6e39e09cb0e7ab385a5c0fb2abe8a073eb).
